# -*- coding: utf-8 -*-
"""Pratique1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E5JZTBQqoluGQg2WysJguESIcUAzjlSK

# Calculadora
"""

continuar = "Sim"

while continuar == "Sim":

    num1 = float(input("Digite o primeiro número: "))
    num2 = float(input("Digite o segundo número: "))


    print("Escolha a operação:")
    print("1 - Soma")
    print("2 - Subtração")
    print("3 - Multiplicação")
    print("4 - Divisão")

    opcao = input("Digite o número da operação desejada: ")


    if opcao == "1":
        resultado = num1 + num2
        print(f"Resultado: {num1} + {num2} = {resultado}")
    elif opcao == "2":
        resultado = num1 - num2
        print(f"Resultado: {num1} - {num2} = {resultado}")
    elif opcao == "3":
        resultado = num1 * num2
        print(f"Resultado: {num1} * {num2} = {resultado}")
    elif opcao == "4":
        if num2 != 0:
            resultado = num1 / num2
            print(f"Resultado: {num1} / {num2} = {resultado}")
        else:
            print("Erro: divisão por zero não é permitida.")
    else:
        print("Opção inválida!")


    continuar = input("Deseja fazer outra operação? (Sim ou Não): ")

print("Calculadora encerrada. Até mais!")